---
- name: emerge gentoo sources
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; emerge gentoo-sources'
  args:
    creates: /mnt/gentoo/usr/src/linux/arch

- name: eselect profile list
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; eselect profile list'
  register: profile_list
  changed_when: False
  check_mode: no

- debug:
    var: profile_list

- name: Copy kernel config
  copy:
    src: config-4.9.34-gentoo
    dest: /mnt/gentoo/usr/src/linux/.config
    force: no

- name: Run make oldconfig
  command: chroot /mnt/gentoo bash -c 'source /etc/profile; cd /usr/src/linux; make oldconfig'

- name: Copy Kernel config
  template:
    src: config
    dest: /mnt/gentoo/usr/src/linux/.config
  when: ansible_system_vendor == "QEMU"

- name: Make Kernel
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make -j{{ ansible_processor_vcpus+1 }}'

- name: Make Module Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make modules_install'

- name: Make Install
  command: chroot /mnt/gentoo/ bash -c 'source /etc/profile; cd /usr/src/linux; make install'
