---
- name: Reboot system
  shell: sleep 1 && reboot
  async: 1
  poll: 0

- name: Wait for the reboot to complete
  wait_for:
    port: 222
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    connect_timeout: 5
    sleep: 5
    delay: 10
    timeout: 300
  connection: local
