---
- name: Select only SATA disks
  set_fact:
    sata_disks: "[{% for device in ansible_devices %}
      {% if ansible_devices[device].vendor in  ['ATA','QEMU'] and ansible_devices[device].removable == '0' %}
        '{{ device }}',
      {% endif %}
    {% endfor %}]"
- name: Set partition flags
  set_fact:
    partition_flags: "{% if configure_raid == True %}['raid']{% else %}['lvm']{% endif %}"
- name: Create new disc label and BIOS boot partition
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: bios
    number: 1
    part_type: primary
    state: present
    flags:
    - bios_grub
    part_start: 2048s
    part_end: 10239s
    unit: s
  with_items: "{{ sata_disks }}"
- name: Create partition /boot
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: boot
    number: 2
    part_type: primary
    state: present
    flags: "{{ partition_flags }}"
    part_start: 10240s
    part_end: 1058815s
    unit: s
  with_items: "{{ sata_disks }}"
- name: Create partition for crypt
  parted:
    device: "/dev/{{ item }}"
    label: gpt
    name: crypt
    number: 3
    part_type: primary
    state: present
    flags: "{{ partition_flags }}"
    part_start: 1058816s
    unit: s
  with_items: "{{ sata_disks }}"
